<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PeticionesPilotosWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PeticionesPilotosWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PeticionesPilotosWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://PeticionesPiloto/">
    <import location="http://desktop-rdnf1pr:8080/Pilotos/PeticionesPilotos?wsdl" namespace="http://PeticionesPiloto/"/>
    <plnk:partnerLinkType name="PeticionesPilotosLinkType">
        <plnk:role name="PeticionesPilotosRole" portType="ns:PeticionesPilotos"/>
    </plnk:partnerLinkType>
</definitions>
