<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PeticionesClienteWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/PeticionesClienteWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/PeticionesClienteWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://PeticionesCliente/">
    <import location="http://desktop-rdnf1pr:8080/Clientes/PeticionesCliente?wsdl" namespace="http://PeticionesCliente/"/>
    <plnk:partnerLinkType name="PeticionesClienteLinkType">
        <plnk:role name="PeticionesClienteRole" portType="ns:PeticionesCliente"/>
    </plnk:partnerLinkType>
</definitions>
